### ISSUE TITLE
socket io hosting recommendation

### ISSUE THREAD

**Issue by headwinds** [maximevaillancourt/turven#8]
this is a really nice project - I'm just curious where are you hosting the server? I've had trouble finding a good socketio host...

Sometimes you see developer list the host in their readme like if you're using heroku or digital ocean... or ???

**Comment by maximevaillancourt** [comment]
Hey Brandon 👋 

Turven is deployed to Heroku. You should be able to simply push code in this repository to a Heroku origin (or connect the repository to Heroku for automatic deploys), and it should "just work". 🙂

**Comment by headwinds** [comment]
awesome @maximevaillancourt  - I'm currently using Vercel and have to had use Pusher instead of Socketio - good to know its easy to setup on Heroku - much thanks!
